stages:
    - react_build 
    - auto_deploy
    - react_test 

reactBuild:
    image: node
    stage: react_build
    only:
        - master
    script:
        - echo "start building app"
        - npm install
        - npm build
        - echo "build successful"
reactTest:
    stage: react_test
    image: node 
    only:
        - master
    script:
        - echo "testing app"

# autoDeploy: 
#     stage: auto_deploy 
#     only:
#     - master
#     script:
#         - #TODO
#         - #TODO
